apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dm-shop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenvanhung10111997/gitops.git
    targetRevision: master
    path: apps/dm-shop
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
